/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as applicationRouteRouteImport } from './routes/(application)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as applicationIndexRouteImport } from './routes/(application)/index'
import { Route as applicationInviteRouteImport } from './routes/(application)/invite'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const applicationRouteRoute = applicationRouteRouteImport.update({
  id: '/(application)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const applicationIndexRoute = applicationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => applicationRouteRoute,
} as any)
const applicationInviteRoute = applicationInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => applicationRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/invite': typeof applicationInviteRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof applicationIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/invite': typeof applicationInviteRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof applicationIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(application)': typeof applicationRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(application)/invite': typeof applicationInviteRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/api/health': typeof ApiHealthRoute
  '/(application)/': typeof applicationIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/sign-in'
    | '/api/health'
    | '/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/sign-in'
    | '/api/health'
    | '/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/(application)'
    | '/(auth)'
    | '/(application)/invite'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/api/health'
    | '/(application)/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  applicationRouteRoute: typeof applicationRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(application)': {
      id: '/(application)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof applicationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(application)/': {
      id: '/(application)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof applicationIndexRouteImport
      parentRoute: typeof applicationRouteRoute
    }
    '/(application)/invite': {
      id: '/(application)/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof applicationInviteRouteImport
      parentRoute: typeof applicationRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface applicationRouteRouteChildren {
  applicationInviteRoute: typeof applicationInviteRoute
  applicationIndexRoute: typeof applicationIndexRoute
}

const applicationRouteRouteChildren: applicationRouteRouteChildren = {
  applicationInviteRoute: applicationInviteRoute,
  applicationIndexRoute: applicationIndexRoute,
}

const applicationRouteRouteWithChildren =
  applicationRouteRoute._addFileChildren(applicationRouteRouteChildren)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  applicationRouteRoute: applicationRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
