export const maximumLines = 300;

export const sourceRoots = ["apps", "packages", "scripts", "tests"];

export const sourceExtensions = new Set([
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".css",
]);

export const excludedDirectories = new Set([
  "node_modules",
  "dist",
  "coverage",
]);

// These files are regenerated by tools; their source of truth lives elsewhere.
export const generatedPaths = [
  "apps/web/src/routeTree.gen.ts",
  "packages/server/src/codex/protocol/",
];
